CREATE TABLE Orders
(
Id INT NOT NULL  PRIMARY KEY,
SurName VARCHAR(45) NOT NULL,
Name VARCHAR(45) NOT NULL,
MiddleName VARCHAR(45) DEFAULT 0,
SeriaPasport INT NOT NULL,
NumberPasport INT NOT NULL,
Birthday DATE NOT NULL
);

CREATE TABLE Flies
(
Id INT NOT NULL  PRIMARY KEY,
NumberFly INT NOT NULL,
FromWhere VARCHAR(45) NOT NULL,
ToWhere VARCHAR(45) NOT NULL,
Price INT NOT NULL,
PlaneId INT NOT NULL,
TimeInFly TIME NOT NULL,
Time TIME NOT NULL,
CONSTRAINT fk_Plane FOREIGN KEY (PlaneId) REFERENCES Plane(Id)
);

CREATE TABLE Tickets
(
Id INT NOT NULL  PRIMARY KEY,
Place INT NOT NULL,
OrderId INT NOT NULL,
DateFly DATE NOT NULL,
CONSTRAINT fk_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id)
);

CREATE TABLE Plane
(
Id INT NOT NULL  PRIMARY KEY,
PilotId INT NOT NULL UNIQUE,
AmountPlace INT NOT NULL
);

CREATE TABLE Registration
(
Id INT NOT NULL  PRIMARY KEY,
FliesId INT NOT NULL,
TicketId INT NOT NULL,
State INT NOT NULL DEFAULT 0,
CONSTRAINT fk_Flies FOREIGN KEY (FliesId) REFERENCES Flies(Id),
CONSTRAINT fk_Ticket FOREIGN KEY (TicketId) REFERENCES Tickets(Id)
);
