CREATE TABLE Orders
(
IdOrders INT NOT NULL  PRIMARY KEY,
SirName VARCHAR(45) NOT NULL,
Name VARCHAR(45) NOT NULL,
MiddleName VARCHAR(45) DEFAULT 0,
SeriaPasport INT NOT NULL,
NumberPasport INT NOT NULL,
Birthday DATE NOT NULL
);

CREATE TABLE Flies
(
IdFlies INT NOT NULL  PRIMARY KEY,
NumberFly INT NOT NULL,
FromWhere VARCHAR(45) NOT NULL,
ToWhere VARCHAR(45) NOT NULL,
Price INT NOT NULL,
PlaneId INT NOT NULL,
TimeInFly TIME NOT NULL,
TimeToFly TIME NOT NULL,
CONSTRAINT fk_Plane FOREIGN KEY (PlaneId) REFERENCES Plane(IdPlane)
);

CREATE TABLE Tickets
(
IdTicket INT NOT NULL  PRIMARY KEY,
Place INT NOT NULL,
OrderId INT NOT NULL,
DateFly DATE NOT NULL,
CONSTRAINT fk_Order FOREIGN KEY (OrderId) REFERENCES Orders(IdOrders)
);

CREATE TABLE Plane
(
IdPlane INT NOT NULL  PRIMARY KEY,
PilotId INT NOT NULL UNIQUE,
AmountPlace INT NOT NULL
);

CREATE TABLE Registration
(
IdFly INT NOT NULL  PRIMARY KEY,
FliesId INT NOT NULL,
TicketId INT NOT NULL,
State INT NOT NULL DEFAULT -1,
CONSTRAINT fk_Flies FOREIGN KEY (FliesId) REFERENCES Flies(IdFlies),
CONSTRAINT fk_Ticket FOREIGN KEY (TicketId) REFERENCES Tickets(IdTicket)
);
