CREATE DATABASE port;
USE `port`;
DROP Table IF EXISTS Orders;
CREATE TABLE Orders
(
Id INT NOT NULL  PRIMARY KEY,
SurName VARCHAR(45) NOT NULL,
Name VARCHAR(45) NOT NULL,
MiddleName VARCHAR(45) DEFAULT 0,
SeriaPasport VARCHAR(4) NOT NULL,
NumberPasport VARCHAR(6) NOT NULL,
Birthday DATE NOT NULL,
CHECK (Id>0)
);
DROP TABLE IF EXISTS Plane;
CREATE TABLE Plane
(
Id INT NOT NULL  PRIMARY KEY,
PilotId INT NOT NULL UNIQUE,
AmountPlace TINYINT NOT NULL,
CHECK (Id>0)
);
DROP TABLE IF EXISTS Flies;
CREATE TABLE Flies
(
Id INT NOT NULL  PRIMARY KEY,
NumberFly INT NOT NULL,
FromWhere VARCHAR(45) NOT NULL,
ToWhere VARCHAR(45) NOT NULL,
Price INT NOT NULL,
PlaneId INT NOT NULL,
TimeInFly TIME NOT NULL,
Time TIME NOT NULL,
CHECK (Price>0),
CHECK (Id>0),
CONSTRAINT fk_Plane FOREIGN KEY (PlaneId) REFERENCES Plane(Id) 
);
DROP TABLE IF EXISTS Tickets;
CREATE TABLE Tickets
(
Id INT NOT NULL  PRIMARY KEY,
Place TINYINT NOT NULL,
OrderId INT NOT NULL,
DateFly DATE NOT NULL,
FliesId INT NOT NULL,
CHECK (Id>0),
CONSTRAINT fk_Order FOREIGN KEY (OrderId) REFERENCES Orders(Id),
CONSTRAINT fk_Flies FOREIGN KEY (FliesId) REFERENCES Flies(Id)
);
DROP TABLE IF EXISTS Registration;
CREATE TABLE Registration
(
Id INT NOT NULL  PRIMARY KEY,
TicketId INT NOT NULL,
State INT NOT NULL DEFAULT 0,
CHECK (Id>0),
CONSTRAINT fk_Ticket FOREIGN KEY (TicketId) REFERENCES Tickets(Id)
);
